// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxbEHJGE9h6KkSZ0zTlAlaUFSqG6a_Dc',
    appId: '1:711309013026:web:373d17d87a29bc89ec9a7b',
    messagingSenderId: '711309013026',
    projectId: 'patha-2305',
    authDomain: 'patha-2305.firebaseapp.com',
    storageBucket: 'patha-2305.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2AToXGMZzjaUcsnDcP8ILBtAHlZyuxc',
    appId: '1:711309013026:android:7c79708183ab9c74ec9a7b',
    messagingSenderId: '711309013026',
    projectId: 'patha-2305',
    storageBucket: 'patha-2305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB281Bnjk8lXj4T31eFw0cBo2V6s3ceeS8',
    appId: '1:711309013026:ios:3e769c158a1e30f2ec9a7b',
    messagingSenderId: '711309013026',
    projectId: 'patha-2305',
    storageBucket: 'patha-2305.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB281Bnjk8lXj4T31eFw0cBo2V6s3ceeS8',
    appId: '1:711309013026:ios:3e769c158a1e30f2ec9a7b',
    messagingSenderId: '711309013026',
    projectId: 'patha-2305',
    storageBucket: 'patha-2305.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxbEHJGE9h6KkSZ0zTlAlaUFSqG6a_Dc',
    appId: '1:711309013026:web:d775e478a40b3629ec9a7b',
    messagingSenderId: '711309013026',
    projectId: 'patha-2305',
    authDomain: 'patha-2305.firebaseapp.com',
    storageBucket: 'patha-2305.firebasestorage.app',
  );
}
